export class PaisesModelo {
    public static Paises: any = [
        { id: 'AD', Nombre: 'Andorra'},
        { id: 'AE', Nombre: 'United Arab Emirates'},
        { id: 'AF', Nombre: 'Afghanistan'},
        { id: 'AG', Nombre: 'Antigua and Barbuda'},
        { id: 'AL', Nombre: 'Albania'},
        { id: 'AM', Nombre: 'Armenia'},
        { id: 'AO', Nombre: 'Angola'},
        { id: 'AR', Nombre: 'Argentina'},
        { id: 'AT', Nombre: 'Austria'},
        { id: 'AU', Nombre: 'Australia'},
        { id: 'AZ', Nombre: 'Azerbaijan'},
        { id: 'BA', Nombre: 'Bosnia and Herzegovina'},
        { id: 'BB', Nombre: 'Barbados'},
        { id: 'BD', Nombre: 'Bangladesh'},
        { id: 'BE', Nombre: 'Belgium'},
        { id: 'BF', Nombre: 'Burkina Faso'},
        { id: 'BG', Nombre: 'Bulgaria'},
        { id: 'BH', Nombre: 'Bahrain'},
        { id: 'BI', Nombre: 'Burundi'},
        { id: 'BJ', Nombre: 'Benin'},
        { id: 'BN', Nombre: 'Brunei'},
        { id: 'BO', Nombre: 'Bolivia'},
        { id: 'BR', Nombre: 'Brazil'},
        { id: 'BS', Nombre: 'Bahamas'},
        { id: 'BT', Nombre: 'Bhutan'},
        { id: 'BW', Nombre: 'Botswana'},
        { id: 'BY', Nombre: 'Belarus'},
        { id: 'BZ', Nombre: 'Belize'},
        { id: 'CA', Nombre: 'Canada'},
        { id: 'CD', Nombre: 'Congo, Democratic Republic of'},
        { id: 'CF', Nombre: 'Central African Republic'},
        { id: 'CG', Nombre: 'Congo, Republic of'},
        { id: 'CH', Nombre: 'Switzerland'},
        { id: 'CL', Nombre: 'Chile'},
        { id: 'CM', Nombre: 'Cameroon'},
        { id: 'CN', Nombre: 'China, The Peoples Republic of'},
        { id: 'CO', Nombre: 'Colombia'},
        { id: 'CR', Nombre: 'Costa Rica'},
        { id: 'CU', Nombre: 'Cuba'},
        { id: 'CV', Nombre: 'Cape Verde'},
        { id: 'CY', Nombre: 'Cyprus'},
        { id: 'CZ', Nombre: 'Czech Republic'},
        { id: 'DE', Nombre: 'Germany'},
        { id: 'DJ', Nombre: 'Djibouti'},
        { id: 'DK', Nombre: 'Denmark'},
        { id: 'DM', Nombre: 'Dominica'},
        { id: 'DO', Nombre: 'Dominican Republic'},
        { id: 'DZ', Nombre: 'Algeria'},
        { id: 'EC', Nombre: 'Ecuador'},
        { id: 'EE', Nombre: 'Estonia'},
        { id: 'EG', Nombre: 'Egypt'},
        { id: 'ER', Nombre: 'Eritrea'},
        { id: 'ES', Nombre: 'Spain'},
        { id: 'ET', Nombre: 'Ethiopia'},
        { id: 'FI', Nombre: 'Finland'},
        { id: 'FJ', Nombre: 'Fiji'},
        { id: 'FM', Nombre: 'Micronesia, Federated States of'},
        { id: 'FR', Nombre: 'France'},
        { id: 'GA', Nombre: 'Gabon'},
        { id: 'GD', Nombre: 'Grenada'},
        { id: 'GE', Nombre: 'Georgia'},
        { id: 'GH', Nombre: 'Ghana'},
        { id: 'GM', Nombre: 'Gambia'},
        { id: 'GN', Nombre: 'Guinea'},
        { id: 'GQ', Nombre: 'Equatorial Guinea'},
        { id: 'GR', Nombre: 'Greece'},
        { id: 'GT', Nombre: 'Guatemala'},
        { id: 'GW', Nombre: 'Guinea-bissau'},
        { id: 'GY', Nombre: 'Guyana'},
        { id: 'HN', Nombre: 'Honduras'},
        { id: 'HR', Nombre: 'Croatia'},
        { id: 'HT', Nombre: 'Haiti'},
        { id: 'HU', Nombre: 'Hungary'},
        { id: 'ID', Nombre: 'Indonesia'},
        { id: 'IE', Nombre: 'Ireland'},
        { id: 'IL', Nombre: 'Israel'},
        { id: 'IN', Nombre: 'India'},
        { id: 'IQ', Nombre: 'Iraq'},
        { id: 'IR', Nombre: 'Iran'},
        { id: 'IS', Nombre: 'Iceland'},
        { id: 'IT', Nombre: 'Italy'},
        { id: 'JA', Nombre: 'Jamaica'},
        { id: 'JO', Nombre: 'Jordan'},
        { id: 'JP', Nombre: 'Japan'},
        { id: 'KE', Nombre: 'Kenya'},
        { id: 'KG', Nombre: 'Kyrgyzstan'},
        { id: 'KH', Nombre: 'Cambodia'},
        { id: 'KI', Nombre: 'Kiribati'},
        { id: 'KM', Nombre: 'Comoros'},
        { id: 'KN', Nombre: 'Saint Kitts and Nevis'},
        { id: 'KP', Nombre: 'Korea, Democratic Peoples Republic (north)'},
        { id: 'KR', Nombre: 'Korea, Republic  (south)'},
        { id: 'KW', Nombre: 'Kuwait'},
        { id: 'KZ', Nombre: 'Kazakhstan'},
        { id: 'LB', Nombre: 'Lebanon'},
        { id: 'LC', Nombre: 'Saint Lucia'},
        { id: 'LI', Nombre: 'Liechtenstein'},
        { id: 'LK', Nombre: 'Sri Lanka'},
        { id: 'LR', Nombre: 'Liberia'},
        { id: 'LS', Nombre: 'Lesotho'},
        { id: 'LT', Nombre: 'Lithuania'},
        { id: 'LU', Nombre: 'Luxembourg'},
        { id: 'LV', Nombre: 'Latvia'},
        { id: 'LY', Nombre: 'Libya'},
        { id: 'MA', Nombre: 'Morocco'},
        { id: 'MC', Nombre: 'Monaco'},
        { id: 'MD', Nombre: 'Moldova'},
        { id: 'ME', Nombre: 'MONTENEGRO'},
        { id: 'MG', Nombre: 'Madagascar'},
        { id: 'MH', Nombre: 'Marshall Islands'},
        { id: 'MK', Nombre: 'Macedonia'},
        { id: 'ML', Nombre: 'Mali'},
        { id: 'MN', Nombre: 'Mongolia'},
        { id: 'MR', Nombre: 'Mauritania'},
        { id: 'MT', Nombre: 'Malta'},
        { id: 'MU', Nombre: 'Mauritius'},
        { id: 'MV', Nombre: 'Maldives'},
        { id: 'MW', Nombre: 'Malawi'},
        { id: 'MX', Nombre: 'Mexico'},
        { id: 'MY', Nombre: 'Malaysia'},
        { id: 'MZ', Nombre: 'Mozambique'},
        { id: 'NA', Nombre: 'Namibia'},
        { id: 'NE', Nombre: 'Niger'},
        { id: 'NG', Nombre: 'Nigeria'},
        { id: 'NI', Nombre: 'Nicaragua'},
        { id: 'NL', Nombre: 'Netherlands'},
        { id: 'NO', Nombre: 'Norway'},
        { id: 'NP', Nombre: 'Nepal'},
        { id: 'NR', Nombre: 'Nauru'},
        { id: 'NZ', Nombre: 'New Zealand'},
        { id: 'OM', Nombre: 'Oman'},
        { id: 'PA', Nombre: 'Panama'},
        { id: 'PE', Nombre: 'Peru'},
        { id: 'PG', Nombre: 'Papua New Guinea'},
        { id: 'PH', Nombre: 'Philippines'},
        { id: 'PK', Nombre: 'Pakistan'},
        { id: 'PL', Nombre: 'Poland'},
        { id: 'PT', Nombre: 'Portugal'},
        { id: 'PW', Nombre: 'Palau'},
        { id: 'PY', Nombre: 'Paraguay'},
        { id: 'QA', Nombre: 'Qatar'},
        { id: 'RO', Nombre: 'Romania'},
        { id: 'RS', Nombre: 'SERBIA'},
        { id: 'RU', Nombre: 'Russia'},
        { id: 'RW', Nombre: 'Rwanda'},
        { id: 'SA', Nombre: 'Saudi Arabia'},
        { id: 'SB', Nombre: 'Solomon Islands'},
        { id: 'SC', Nombre: 'Seychelles'},
        { id: 'SD', Nombre: 'Sudan'},
        { id: 'SE', Nombre: 'Sweden'},
        { id: 'SG', Nombre: 'Singapore'},
        { id: 'SI', Nombre: 'Slovenia'},
        { id: 'SK', Nombre: 'Slovakia'},
        { id: 'SL', Nombre: 'Sierra Leone'},
        { id: 'SM', Nombre: 'San marino'},
        { id: 'SN', Nombre: 'Senegal'},
        { id: 'SO', Nombre: 'Somalia'},
        { id: 'SR', Nombre: 'Suriname'},
        { id: 'SS', Nombre: 'SOUTH SUDAN'},
        { id: 'ST', Nombre: 'São Tomé and Príncipe'},
        { id: 'SV', Nombre: 'El Salvador'},
        { id: 'SY', Nombre: 'Syria'},
        { id: 'SZ', Nombre: 'Swaziland'},
        { id: 'TD', Nombre: 'Chad'},
        { id: 'TG', Nombre: 'Togo'},
        { id: 'TH', Nombre: 'Thailand'},
        { id: 'TJ', Nombre: 'Tajikistan'},
        { id: 'TL', Nombre: 'East Timor'},
        { id: 'TM', Nombre: 'Turkmenistan'},
        { id: 'TN', Nombre: 'Tunisia'},
        { id: 'TO', Nombre: 'Tonga'},
        { id: 'TR', Nombre: 'Turkey'},
        { id: 'TT', Nombre: 'Trinidad and Tobago'},
        { id: 'TV', Nombre: 'Tuvalu'},
        { id: 'TZ', Nombre: 'Tanzania'},
        { id: 'UA', Nombre: 'Ukraine'},
        { id: 'UG', Nombre: 'Uganda'},
        { id: 'UK', Nombre: 'United Kingdom'},
        { id: 'US', Nombre: 'United States of America'},
        { id: 'UY', Nombre: 'Uruguay'},
        { id: 'UZ', Nombre: 'Uzbekistan'},
        { id: 'VC', Nombre: 'SAINT VINCENT AND THE GRENADINES'},
        { id: 'VE', Nombre: 'Venezuela'},
        { id: 'VN', Nombre: 'Vietnam'},
        { id: 'VU', Nombre: 'Vanuatu'},
        { id: 'WS', Nombre: 'Samoa'},
        { id: 'YE', Nombre: 'Yemen'},
        { id: 'ZA', Nombre: 'South Africa'},
        { id: 'ZM', Nombre: 'Zambia'},
        { id: 'ZW', Nombre: 'Zimbabwe'}
    ]
}