export class PaisesModelo {
    public static Paises: any = [
        { id: 'AF' , Nombre: 'Afghanistan'},
        { id: 'AL' , Nombre: 'Albania'},
        { id: 'DZ' , Nombre: 'Algeria'},
        { id: 'AD' , Nombre: 'Andorra'},
        { id: 'AO' , Nombre: 'Angola'},
        { id: 'AG' , Nombre: 'Antigua and Barbuda'},
        { id: 'AR' , Nombre: 'Argentina'},
        { id: 'AM' , Nombre: 'Armenia'},
        { id: 'AU' , Nombre: 'Australia'},
        { id: 'AT' , Nombre: 'Austria'},
        { id: 'AZ' , Nombre: 'Azerbaijan'},
        { id: 'BS' , Nombre: 'Bahamas'},
        { id: 'BH' , Nombre: 'Bahrain'},
        { id: 'BD' , Nombre: 'Bangladesh'},
        { id: 'BB' , Nombre: 'Barbados'},
        { id: 'BY' , Nombre: 'Belarus'},
        { id: 'BE' , Nombre: 'Belgium'},
        { id: 'BZ' , Nombre: 'Belize'},
        { id: 'BJ' , Nombre: 'Benin'},
        { id: 'BT' , Nombre: 'Bhutan'},
        { id: 'BO' , Nombre: 'Bolivia'},
        { id: 'BA' , Nombre: 'Bosnia and Herzegovina'},
        { id: 'BW' , Nombre: 'Botswana'},
        { id: 'BR' , Nombre: 'Brazil'},
        { id: 'BN' , Nombre: 'Brunei'},
        { id: 'BG' , Nombre: 'Bulgaria'},
        { id: 'BF' , Nombre: 'Burkina Faso'},
        { id: 'BI' , Nombre: 'Burundi'},
        { id: 'KH' , Nombre: 'Cambodia'},
        { id: 'CM' , Nombre: 'Cameroon'},
        { id: 'CA' , Nombre: 'Canada'},
        { id: 'CV' , Nombre: 'Cape Verde'},
        { id: 'CF' , Nombre: 'Central African Republic'},
        { id: 'TD' , Nombre: 'Chad'},
        { id: 'CL' , Nombre: 'Chile'},
        { id: 'CN' , Nombre: 'China, The Peoples Republic of'},
        { id: 'CO' , Nombre: 'Colombia'},
        { id: 'KM' , Nombre: 'Comoros'},
        { id: 'CD' , Nombre: 'Congo, Democratic Republic of'},
        { id: 'CG' , Nombre: 'Congo, Republic of'},
        { id: 'CR' , Nombre: 'Costa Rica'},
        { id: 'HR' , Nombre: 'Croatia'},
        { id: 'CU' , Nombre: 'Cuba'},
        { id: 'CY' , Nombre: 'Cyprus'},
        { id: 'CZ' , Nombre: 'Czech Republic'},
        { id: 'DK' , Nombre: 'Denmark'},
        { id: 'DJ' , Nombre: 'Djibouti'},
        { id: 'DM' , Nombre: 'Dominica'},
        { id: 'DO' , Nombre: 'Dominican Republic'},
        { id: 'TL' , Nombre: 'East Timor'},
        { id: 'EC' , Nombre: 'Ecuador'},
        { id: 'EG' , Nombre: 'Egypt'},
        { id: 'SV' , Nombre: 'El Salvador'},
        { id: 'GQ' , Nombre: 'Equatorial Guinea'},
        { id: 'ER' , Nombre: 'Eritrea'},
        { id: 'EE' , Nombre: 'Estonia'},
        { id: 'ET' , Nombre: 'Ethiopia'},
        { id: 'FJ' , Nombre: 'Fiji'},
        { id: 'FI' , Nombre: 'Finland'},
        { id: 'FR' , Nombre: 'France'},
        { id: 'GA' , Nombre: 'Gabon'},
        { id: 'GM' , Nombre: 'Gambia'},
        { id: 'GE' , Nombre: 'Georgia'},
        { id: 'DE' , Nombre: 'Germany'},
        { id: 'GH' , Nombre: 'Ghana'},
        { id: 'GR' , Nombre: 'Greece'},
        { id: 'GD' , Nombre: 'Grenada'},
        { id: 'GT' , Nombre: 'Guatemala'},
        { id: 'GN' , Nombre: 'Guinea'},
        { id: 'GW' , Nombre: 'Guinea-bissau'},
        { id: 'GY' , Nombre: 'Guyana'},
        { id: 'HT' , Nombre: 'Haiti'},
        { id: 'HN' , Nombre: 'Honduras'},
        { id: 'HU' , Nombre: 'Hungary'},
        { id: 'IS' , Nombre: 'Iceland'},
        { id: 'IN' , Nombre: 'India'},
        { id: 'ID' , Nombre: 'Indonesia'},
        { id: 'IR' , Nombre: 'Iran'},
        { id: 'IQ' , Nombre: 'Iraq'},
        { id: 'IE' , Nombre: 'Ireland'},
        { id: 'IL' , Nombre: 'Israel'},
        { id: 'IT' , Nombre: 'Italy'},
        { id: 'JA' , Nombre: 'Jamaica'},
        { id: 'JP' , Nombre: 'Japan'},
        { id: 'JO' , Nombre: 'Jordan'},
        { id: 'KZ' , Nombre: 'Kazakhstan'},
        { id: 'KE' , Nombre: 'Kenya'},
        { id: 'KI' , Nombre: 'Kiribati'},
        { id: 'KP' , Nombre: 'Korea, Democratic Peoples Republic (north)'},
        { id: 'KR' , Nombre: 'Korea, Republic  (south)'},
        { id: 'KW' , Nombre: 'Kuwait'},
        { id: 'KG' , Nombre: 'Kyrgyzstan'},
        { id: 'LV' , Nombre: 'Latvia'},
        { id: 'LB' , Nombre: 'Lebanon'},
        { id: 'LS' , Nombre: 'Lesotho'},
        { id: 'LR' , Nombre: 'Liberia'},
        { id: 'LY' , Nombre: 'Libya'},
        { id: 'LI' , Nombre: 'Liechtenstein'},
        { id: 'LT' , Nombre: 'Lithuania'},
        { id: 'LU' , Nombre: 'Luxembourg'},
        { id: 'MK' , Nombre: 'Macedonia'},
        { id: 'MG' , Nombre: 'Madagascar'},
        { id: 'MW' , Nombre: 'Malawi'},
        { id: 'MY' , Nombre: 'Malaysia'},
        { id: 'MV' , Nombre: 'Maldives'},
        { id: 'ML' , Nombre: 'Mali'},
        { id: 'MT' , Nombre: 'Malta'},
        { id: 'MH' , Nombre: 'Marshall Islands'},
        { id: 'MR' , Nombre: 'Mauritania'},
        { id: 'MU' , Nombre: 'Mauritius'},
        { id: 'MX' , Nombre: 'Mexico'},
        { id: 'FM' , Nombre: 'Micronesia, Federated States of'},
        { id: 'MD' , Nombre: 'Moldova'},
        { id: 'MC' , Nombre: 'Monaco'},
        { id: 'MN' , Nombre: 'Mongolia'},
        { id: 'ME' , Nombre: 'MONTENEGRO'},
        { id: 'MA' , Nombre: 'Morocco'},
        { id: 'MZ' , Nombre: 'Mozambique'},
        { id: 'NA' , Nombre: 'Namibia'},
        { id: 'NR' , Nombre: 'Nauru'},
        { id: 'NP' , Nombre: 'Nepal'},
        { id: 'NL' , Nombre: 'Netherlands'},
        { id: 'NZ' , Nombre: 'New Zealand'},
        { id: 'NI' , Nombre: 'Nicaragua'},
        { id: 'NE' , Nombre: 'Niger'},
        { id: 'NG' , Nombre: 'Nigeria'},
        { id: 'NO' , Nombre: 'Norway'},
        { id: 'OM' , Nombre: 'Oman'},
        { id: 'PK' , Nombre: 'Pakistan'},
        { id: 'PW' , Nombre: 'Palau'},
        { id: 'PA' , Nombre: 'Panama'},
        { id: 'PG' , Nombre: 'Papua New Guinea'},
        { id: 'PY' , Nombre: 'Paraguay'},
        { id: 'PE' , Nombre: 'Peru'},
        { id: 'PH' , Nombre: 'Philippines'},
        { id: 'PL' , Nombre: 'Poland'},
        { id: 'PT' , Nombre: 'Portugal'},
        { id: 'QA' , Nombre: 'Qatar'},
        { id: 'RO' , Nombre: 'Romania'},
        { id: 'RU' , Nombre: 'Russia'},
        { id: 'RW' , Nombre: 'Rwanda'},
        { id: 'KN' , Nombre: 'Saint Kitts and Nevis'},
        { id: 'LC' , Nombre: 'Saint Lucia'},
        { id: 'VC' , Nombre: 'SAINT VINCENT AND THE GRENADINES'},
        { id: 'WS' , Nombre: 'Samoa'},
        { id: 'SM' , Nombre: 'San marino'},
        { id: 'ST' , Nombre: 'São Tomé and Príncipe'},
        { id: 'SA' , Nombre: 'Saudi Arabia'},
        { id: 'SN' , Nombre: 'Senegal'},
        { id: 'RS' , Nombre: 'SERBIA'},
        { id: 'SC' , Nombre: 'Seychelles'},
        { id: 'SL' , Nombre: 'Sierra Leone'},
        { id: 'SG' , Nombre: 'Singapore'},
        { id: 'SK' , Nombre: 'Slovakia'},
        { id: 'SI' , Nombre: 'Slovenia'},
        { id: 'SB' , Nombre: 'Solomon Islands'},
        { id: 'SO' , Nombre: 'Somalia'},
        { id: 'ZA' , Nombre: 'South Africa'},
        { id: 'SS' , Nombre: 'SOUTH SUDAN'},
        { id: 'ES' , Nombre: 'Spain'},
        { id: 'LK' , Nombre: 'Sri Lanka'},
        { id: 'SD' , Nombre: 'Sudan'},
        { id: 'SR' , Nombre: 'Suriname'},
        { id: 'SZ' , Nombre: 'Swaziland'},
        { id: 'SE' , Nombre: 'Sweden'},
        { id: 'CH' , Nombre: 'Switzerland'},
        { id: 'SY' , Nombre: 'Syria'},
        { id: 'TJ' , Nombre: 'Tajikistan'},
        { id: 'TZ' , Nombre: 'Tanzania'},
        { id: 'TH' , Nombre: 'Thailand'},
        { id: 'TG' , Nombre: 'Togo'},
        { id: 'TO' , Nombre: 'Tonga'},
        { id: 'TT' , Nombre: 'Trinidad and Tobago'},
        { id: 'TN' , Nombre: 'Tunisia'},
        { id: 'TR' , Nombre: 'Turkey'},
        { id: 'TM' , Nombre: 'Turkmenistan'},
        { id: 'TV' , Nombre: 'Tuvalu'},
        { id: 'UG' , Nombre: 'Uganda'},
        { id: 'UA' , Nombre: 'Ukraine'},
        { id: 'AE' , Nombre: 'United Arab Emirates'},
        { id: 'UK' , Nombre: 'United Kingdom'},
        { id: 'US' , Nombre: 'United States of America'},
        { id: 'UY' , Nombre: 'Uruguay'},
        { id: 'UZ' , Nombre: 'Uzbekistan'},
        { id: 'VU' , Nombre: 'Vanuatu'},
        { id: 'VE' , Nombre: 'Venezuela'},
        { id: 'VN' , Nombre: 'Vietnam'},
        { id: 'YE' , Nombre: 'Yemen'},
        { id: 'ZM' , Nombre: 'Zambia'},
        { id: 'ZW' , Nombre: 'Zimbabwe'}
    ];
}
